repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files # Prevent giant files from being committed
  - id: check-merge-conflict # Check for files that contain merge conflict strings
  - id: check-yaml # Attempts to load all yaml files to verify syntax
  - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
  - id: mixed-line-ending # Replaces or checks mixed line ending
    args: ['--fix=lf']
  - id: trailing-whitespace # Trims trailing whitespace

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.6
  hooks:
  - id: clang-format
    types_or: [c++, c]
    args: [--style=Chromium]

- repo: https://github.com/cpplint/cpplint
  rev: 6f9c205cdafa7698970be14dc840b7f9699ec7fe
  hooks:
  - id: cpplint
    args: ["--filter=-legal/copyright,-build/include_subdir,-build/header_guard,-build/include_what_you_use"]
